### ISSUE TITLE
delegates exists but is empty

### ISSUE THREAD

**Issue by WebFreak001** [dlang-tour/german#26]
should be deleted for now or translated but not being kept with a TODO note so it's easier to see what's missing

**Comment by wilzbach** [comment]
I think it exists due to a link pointing to it which would otherwise result in an error.

**Comment by WebFreak001** [comment]
hm I'm not a big fan of dead links but leading the user to a todo page isn't much better. Maybe disabling the link for now?

**Comment by wilzbach** [comment]
FTR we are talking about this page: https://github.com/dlang-tour/german/blob/74edd517fd7902dfc54ba0c67203386b161e2e56/basics/functions.md#lokale-funktionen and the link at "in der Tiefe".

> Maybe disabling the link for now?

Hmm, that requires keeping a list of links "to be added" which can be forgotten easily.

Well to be honest both ways are ok to me, when I created this page I simply went with the simplest option ;-)

**Comment by wilzbach** [comment]
With https://github.com/dlang-tour/german/pull/40 this should soon no longer be an issue ;-)
